# Generated by Django 3.2.8 on 2023-07-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('carrera', models.CharField(max_length=25)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
