# Generated by Django 3.2.8 on 2023-07-18 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
