# Generated by Django 3.2.8 on 2023-07-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0002_rename_titulo_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(),
        ),
    ]
