# Generated by Django 3.2.8 on 2023-07-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0003_remove_usuario_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='asociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('carrera', models.CharField(max_length=25)),
                ('codigo', models.CharField(default='0000000', max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('tipo_socio', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(default='0000000', max_length=10),
        ),
    ]
