# Generated by Django 3.2.8 on 2023-07-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0004_auto_20230709_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('contenido', models.CharField(max_length=80)),
                ('precio', models.CharField(max_length=15)),
                ('seccion', models.CharField(max_length=20)),
                ('imagen', models.ImageField(upload_to='producto')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('contenido', models.CharField(max_length=80)),
                ('precio', models.CharField(max_length=15)),
                ('seccion', models.CharField(max_length=20)),
                ('imagen', models.ImageField(upload_to='producto')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('contenido', models.CharField(max_length=80)),
                ('precio', models.CharField(max_length=25)),
                ('imagen', models.ImageField(upload_to='servicio')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
