# Generated by Django 3.2.8 on 2023-07-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0005_oferta_producto_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='contenido',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='producto',
            name='contenido',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='contenido',
            field=models.CharField(max_length=350),
        ),
    ]
