# Generated by Django 3.2.8 on 2023-07-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociado', '0006_auto_20230712_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='stock',
            field=models.CharField(default='5', max_length=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.CharField(default='5', max_length=5),
        ),
    ]
